apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: earth-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kpkqOrg/git-ops.git
    targetRevision: HEAD
    path: earth-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: earth-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
