apiVersion: v1
kind: Service
metadata:
  name: earth-app-service
spec:
  type: LoadBalancer
  selector:
    app: earth-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
